### ISSUE TITLE
Questions regarding function declarations

### ISSUE THREAD

**Issue by Rubenisme** [BSVino/JaiPrimer#15]
Why do function declarations require more typing than necessary?

> Function declarations look like this:
> 
> ```
> // A function that accepts 3 floats as parameters and returns a float
> sum := (x: float, y: float, z: float) -> float {
>     return x + y + z;
> };
> ```

I don't see the value in having 

> :=

 or 

> ->

Couldn't it just be:

> sum (x: float, y: float, z: float) : float {
>     return x + y + z;
> }

The declaration of variables is a certain way (like Typescript's), so why not also re-use it for the way functions are declared?

Also, I'm not reading anything regarding visibility (e.g. private, public) of functions/variables. Has this been overlooked or is it on the 'not planned' list?
Typescript has this like:

> protected sum (x: float, y: float, z: float) : float {
>     return x + y + z;
> }

Which I personally do like a lot. Making it easy for people to write less code and clear code, that is easy to understand but powerful and made for good developers is what is wanted right?

**Comment by resistcorp** [comment]
Not an expert but here's my take :
( tl; dr : I think the emphasis of jai is on quick code mutation, rather than quick code typing. )

`(x: float, y: float, z: float) -> float` is a type information just as `float` is. The chunk of code you are referring to is defining a variable of that type. One of the first goals that Mr Blow stated was to have an easier lifecycle for procedures, that it had to be easy to transform a chunk of code into a lambda, then into a _bona fide_ named procedure, and back and forth. I think he chose to use the arrow because it visually conveys the intended meaning of "x->y transforms x into y". Also he has often repeated that the syntax is mostly placeholder, so it could still change.

I think it would be possible to assign a new lambda to the variable `sum` later in the code, but only with a lambda with a type that can be reduced to `(x: float, y: float, z: float) -> float`. A constant procedure can be defined with `name :: (x: float, y: float, z: float) -> float{/*code*/};` (note the `::` instead of `:=`).

As for the visibility, as I understand it, since jai isn't object-_oriented_, protected wouldn't be very meaningful. Beside, Mr Blow doesn't seem to be a big fan of enforcing visibility through language. He has however introduced the concept of scopes in recent videos, which can be seen in his livecoding streams of the dropdown console. So part of a file's code can be scoped to file or to project, but even that seemed to annoy him sometimes :) .

**Comment by BSVino** [comment]
There's really no point in talking about syntax. None of the syntax is final, and even when it's not final, it's the least interesting part of language design.

For what it's worth, the ```->``` part comes from mathematics, where ```f : A -> B``` is a function relating every object of set A to an object of set B. It's common in language design to use ```->``` for that purpose. Also, I think the current syntax is now ```sum :: (a: float, b: float) -> float```, with a ```::``` instead of a ```:=```.

This isn't really an issue with the primer so I'm closing it.
