### ISSUE TITLE
Constructors and destructors should be removed from the "Not Planned" list

### ISSUE THREAD

**Issue by DeRoquefeuille** [BSVino/JaiPrimer#21]
Constructors and Destructors were introduced in the latest demo:

https://www.youtube.com/watch?list=PLmV5I2fxaiCKfxMBrNsU1kgKJXD3PkyxO&v=8C6zuDDGU2w

**Comment by BSVino** [comment]
Done

**Comment by LongBoolean** [comment]
This sentence also mentions constructors/destructors as something not desirable in the language.
>Abstractions like RAII, constructors and destructors, polymorphism, and exceptions were invented with the intention of solving problems that game programmers don’t have, and with the result of interfering with the solutions to problems that game programmers do have.

This could be confusing since the language now has them. Perhaps this should be rephrased to explain how jai constructors are intended to be used differently compared to constructors in other languages. Or perhaps constructors and destructors should not be mentioned here. 

Similarly, the reference to polymorphism may warrant similar action considering issue #8.
